In [1]:
import pandas as pd

In [2]:
msg_1 = pd.read_csv("GLD_2026-06-01_2026-06-11_3/GLD_2026-06-01_34140000_57660000_message_3.csv")
ob_1 = pd.read_csv("GLD_2026-06-01_2026-06-11_3/GLD_2026-06-01_34140000_57660000_orderbook_3.csv")

/var/folders/0b/tfp69kqx3697_bkgxskvksmr0000gn/T/ipykernel_34702/469585337.py:1: DtypeWarning: Columns (0: null) have mixed types. Specify dtype option on import or set low_memory=False.
  msg_1 = pd.read_csv("GLD_2026-06-01_2026-06-11_3/GLD_2026-06-01_34140000_57660000_message_3.csv")

In [8]:
msg_1.head()

   11090.989986489  7       0  0.1        1  -1 null
0     14400.068165  1   27246   40  4680000  -1  NaN
1     14400.090909  1   31546   40  4590000  -1  NaN
2     14403.966856  1  129558    1  4452400  -1  NaN
3     14404.059106  1  130950   12  4094500   1  NaN
4     14414.063773  1  263474    1  4000000   1  NaN

In [6]:
ob_1.tail()

,9999999999,0,-9999999999,0.1,9999999999.1,0.2,-9999999999.1,0.3,9999999999.2,0.4,-9999999999.2,0.5
1067001,4120400,200,4112000,200,9999999999,0,4000000,5,9999999999,0,2600000,30
1067002,4120400,200,4112000,200,9999999999,0,4000000,5,9999999999,0,-9999999999,0
1067003,4120400,200,4112000,200,9999999999,0,-9999999999,0,9999999999,0,-9999999999,0
1067004,9999999999,0,4112000,200,9999999999,0,-9999999999,0,9999999999,0,-9999999999,0
1067005,9999999999,0,-9999999999,0,9999999999,0,-9999999999,0,9999999999,0,-9999999999,0